import pyautogui
import time

pyautogui.hotkey('win')
pyautogui.write('edge')
pyautogui.hotkey('enter')
time.sleep(2)
pyautogui.hotkey('clear')
pyautogui.write('https://favelaware.animahub.com.br/cronograma-2')
time.sleep(3)
pyautogui.hotkey('enter')
time.sleep(3)
pyautogui.hotkey('tab')
pyautogui.hotkey('enter')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('enter')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('enter')